### ISSUE TITLE
ListUploads don't show pending regular uploads

### ISSUE THREAD

**Issue by ifraixedes** [storj/uplink#113] opened 2022-11-03 18:17 UTC
[Project.ListUploads](https://pkg.go.dev/storj.io/uplink#Project.ListUploads) should list all the pending uploads independently if they are regular or multipart uploads.

Currently, the method only shows multipart uploads or regular uploads that have written<sup>1</sup> enough data for not being an inline object.

Acceptance criteria:
* Find the issue of why regular uploads that have not written any data or an amount of data that doesn't create a remote object are listed.
*  Write tests to show up the issue<sup>2</sup>.
* Fix the issue for passing the tests.

---
<sup>1</sup> @Erikvv has reported this when verifying that bug with the PHP bindings.
<sup>2</sup> @ifraixedes wrote a few testsuite tests for showing that list uploads don't work for regular uploads when no data is written. https://review.dev.storj.io/c/storj/uplink/+/8806 The commit is in WIP because the tests don't pass. We can use these tests or write new ones for the fix commit and then rebase this commit on top of the fix commit to seeing if they pass.

**Comment by Erikvv** [comment] 2022-11-04 08:14
Assumption: the cause is that [`ObjectBeginRequest`](https://github.com/storj/common/blob/f2f1c7a50597eb6b0776b28974ae04cd3cecaaae/pb/metainfo.proto#L210) is not sent during `uplink.Project.UploadObject()` but later.

Looking at `ObjectBeginRequest` it does not have a field for inline data. So there is no reason to hold back this request until data is written. It might be a possible future optimization though.

I'm unconvinced this is a guarantee we need to give. The parts or objects should be list-able after calling `uplink.PartUpload.commit()` or `uplink.Upload.Commit()` but it's not necessary to have such guarantees while the object/part is pending.

Thinking ahead, will the next consistency issue be that when uplink.Upload.write("mydata") returns and then you close your program, the data is lost? Because uplink was waiting for either 64 MiB or commit.

I suggest we document at `uplink.Project.UploadObject()` that we have provide no guarantee that a pending object is created and close this issue.

**Comment by mniewrzal** [comment] 2022-11-04 08:30
Standard upload is optimized to make less round-trips to metainfo endpoints. Because of that `ObjectBeginRequest` is sent in a batch with `SegmentBeginRequest`. With multipart uploads client needs to make separate requests to make object and then upload a part. Just after `ObjectBeginRequest` object will be visible while doing `ListUploads`

I agree with @Erikvv that best thing we could do now is improving documentation.

**Comment by ifraixedes** [comment] 2022-11-04 09:31
Improving the documentation looks good to me, it was actually what I posted initially in slack saying that if that's the expected behavior we should update the docs because how currently they are confused about which uploads may not be listed.

**Comment by Erikvv** [comment] 2022-11-04 09:33
https://review.dev.storj.io/c/storj/uplink/+/8809

**Closed** 2022-11-07 14:44 UTC
Labels: bug
